steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/scraping-youtube-feeds',
      '-f', 'docker/Dockerfile',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/scraping-youtube-feeds:latest'
